[package]
name = "passgen"
version = "1.0.0"
authors = ["d.evsyukov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7.3"
colored = "^2.0.0"
clap = "3.0.0-beta.1"
rust-embed="^5.5.1"