[package]
name = "passgen"
version = "1.0.2"
authors = ["Denis Evsyukov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8"
colored = "^2"
structopt = "^0.3"
rust-embed="^6"